import 'dart:ui';

class Singer {
  final String name;
  final String genre;
  final String imageUrl;
  final Color accentColor;
  final String bio;
  final List<String> popularSongs;
  final List<String> albums;

  const Singer({
    required this.name,
    required this.genre,
    required this.imageUrl,
    required this.accentColor,
    required this.bio,
    required this.popularSongs,
    required this.albums,
  });
}

const List<Singer> singers = [
  Singer(
    name: "The Weeknd",
    genre: "R&B / Pop",
    imageUrl: "https://i.pravatar.cc/300?img=11",
    accentColor: Color(0xFF4776E6),
    bio:
        "Abel Makkonen Tesfaye, known as The Weeknd, is a Canadian singer, songwriter, and record producer known for his signature falsetto.",
    popularSongs: const [
      "Blinding Lights",
      "Starboy",
      "Save Your Tears",
      "Die For You",
      "Call Out My Name",
      "Heartless",
      "After Hours",
      "Take My Breath",
      "Sacrifice",
      "Creepin'",
    ],
    albums: const [
      "Dawn FM",
      "After Hours",
      "Starboy",
      "Beauty Behind the Madness",
      "My Dear Melancholy",
      "Kiss Land",
      "House of Balloons",
      "Thursday",
      "Echoes of Silence",
      "The Highlights",
    ],
  ),
  Singer(
    name: "Billie Eilish",
    genre: "Alt / Indie",
    imageUrl: "https://i.pravatar.cc/300?img=5",
    accentColor: Color(0xFF8E54E9),
    bio:
        "Billie Eilish is an American singer-songwriter known for her whispery vocals, dark pop, and emotionally honest songwriting.",
    popularSongs: const [
      "Bad Guy",
      "Birds of a Feather",
      "What Was I Made For?",
      "Lovely",
      "Ocean Eyes",
      "Happier Than Ever",
      "Therefore I Am",
      "Bury a Friend",
      "No Time To Die",
      "Lunch",
    ],
    albums: const [
      "Hit Me Hard and Soft",
      "When We All Fall Asleep...",
      "Happier Than Ever",
      "Don't Smile at Me",
      "GUTS",
      "SOUR",
      "Live at Third Man",
      "Guitar Songs",
      "Barbie",
      "The World Is Burning",
    ],
  ),
  Singer(
    name: "Harry Styles",
    genre: "Soft Rock / Pop",
    imageUrl: "https://i.pravatar.cc/300?img=12",
    accentColor: Color(0xFFF09819),
    bio:
        "Harry Edward Styles is an English singer, songwriter, and actor known for his bold fashion and genre-fluid music.",
    popularSongs: const [
      "As It Was",
      "Watermelon Sugar",
      "Late Night Talking",
      "Sign of the Times",
      "Adore You",
      "Falling",
      "Golden",
      "Kiwi",
      "Lights Up",
      "Music For a Sushi Restaurant",
    ],
    albums: const [
      "Harry's House",
      "Fine Line",
      "Harry Styles",
      "Eroda",
      "Treat People With Kindness",
      "Satellite",
      "Boyfriends",
      "Cinema",
      "One Direction",
      "Please Don't Let Me Go",
    ],
  ),
  Singer(
    name: "Taylor Swift",
    genre: "Pop / Country",
    imageUrl: "https://i.pravatar.cc/300?img=9",
    accentColor: Color(0xFFE94E77),
    bio:
        "Taylor Alison Swift is one of the most influential singer-songwriters of the 21st century, celebrated for her storytelling.",
    popularSongs: const [
      "Cruel Summer",
      "Anti-Hero",
      "Blank Space",
      "Shake It Off",
      "Fortnight",
      "Karma",
      "Lavender Haze",
      "Love Story",
      "You Belong With Me",
      "Cardigan",
    ],
    albums: const [
      "The Tortured Poets Department",
      "Midnights",
      "Folklore",
      "1989",
      "Reputation",
      "Lover",
      "Evermore",
      "Red",
      "Speak Now",
      "Fearless",
    ],
  ),
  Singer(
    name: "Drake",
    genre: "Hip-Hop / Rap",
    imageUrl: "https://i.pravatar.cc/300?img=47",
    accentColor: Color(0xFF1DB954),
    bio:
        "Aubrey Drake Graham is a Canadian rapper, singer, and actor. One of the most successful music artists globally.",
    popularSongs: const [
      "One Dance",
      "God's Plan",
      "Passionfruit",
      "Too Good",
      "Hotline Bling",
      "In My Feelings",
      "Nice For What",
      "Toosie Slide",
      "Laugh Now Cry Later",
      "Jimmy Cooks",
    ],
    albums: const [
      "For All the Dogs",
      "Views",
      "Scorpion",
      "Take Care",
      "Nothing Was the Same",
      "Certified Lover Boy",
      "Her Loss",
      "Honestly, Nevermind",
      "Dark Lane Demo Tapes",
      "If You're Reading This",
    ],
  ),
  Singer(
    name: "Olivia Rodrigo",
    genre: "Pop / Alt",
    imageUrl: "https://i.pravatar.cc/300?img=65",
    accentColor: Color(0xFFFF6B6B),
    bio:
        "Olivia Isabel Rodrigo is an American singer-songwriter and actress who gained massive fame with her emotional debut hits.",
    popularSongs: const [
      "drivers license",
      "vampire",
      "good 4 u",
      "deja vu",
      "traitor",
      "brutal",
      "favorite crime",
      "hope ur ok",
      "lacy",
      "get him back!",
    ],
    albums: const [
      "GUTS",
      "SOUR",
      "GUTS (Spilled)",
      "SOUR (Limited Edition)",
      "drivers license EP",
      "brutal",
      "deja vu",
      "good 4 u",
      "vampire",
      "Olivia Rodrigo Singles",
    ],
  ),
];
