// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyjrv-clBITNEE-4wqwPb4MNWrpx9yEhw',
    appId: '1:188389291755:web:e57848bb807778cdd730ae',
    messagingSenderId: '188389291755',
    projectId: 'cord-library',
    authDomain: 'cord-library.firebaseapp.com',
    storageBucket: 'cord-library.firebasestorage.app',
    measurementId: 'G-DN5D7W9JYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5qs50pwcmm3HNT3ZAqc_kRLWc4dn7tTQ',
    appId: '1:188389291755:android:51f6fceb565dc297d730ae',
    messagingSenderId: '188389291755',
    projectId: 'cord-library',
    storageBucket: 'cord-library.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4LNiShK6dEr2_i5rNc3zGBaTHuug8phQ',
    appId: '1:188389291755:ios:b24a55433188cf69d730ae',
    messagingSenderId: '188389291755',
    projectId: 'cord-library',
    storageBucket: 'cord-library.firebasestorage.app',
    iosBundleId: 'com.example.guitercord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4LNiShK6dEr2_i5rNc3zGBaTHuug8phQ',
    appId: '1:188389291755:ios:b24a55433188cf69d730ae',
    messagingSenderId: '188389291755',
    projectId: 'cord-library',
    storageBucket: 'cord-library.firebasestorage.app',
    iosBundleId: 'com.example.guitercord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyjrv-clBITNEE-4wqwPb4MNWrpx9yEhw',
    appId: '1:188389291755:web:afd3168435a5fbefd730ae',
    messagingSenderId: '188389291755',
    projectId: 'cord-library',
    authDomain: 'cord-library.firebaseapp.com',
    storageBucket: 'cord-library.firebasestorage.app',
    measurementId: 'G-33TKPBW1J8',
  );
}
